const REQUEST_REGISTER = "REQUEST_REGISTER";
const RECIEVE_REGISTER = "RECIEVE_REGISTER";
const REQUEST_LOGIN = "REQUEST_LOGIN";
const RECIEVE_LOGIN = "RECIEVE_LOGIN";
const REQUEST_FETCH_USER = "REQUEST_FETCH_USER";
const RECIEVE_FETCH_USER = "RECIEVE_FETCH_USER";
const REQUEST_UPDATE_PROFILE = "REQUEST_UPDATE_PROFILE";
const RECIEVE_UPDATE_PROFILE = "RECIEVE_UPDATE_PROFILE";

export default {
  REQUEST_REGISTER,
  RECIEVE_REGISTER,
  REQUEST_LOGIN,
  RECIEVE_LOGIN,
  REQUEST_FETCH_USER,
  RECIEVE_FETCH_USER,
  REQUEST_UPDATE_PROFILE,
  RECIEVE_UPDATE_PROFILE
};
