const REQUEST_EDIT_PRODUCT = 'REQUEST_EDIT_PRODUCT';
const RECIEVE_EDIT_PRODUCT = 'RECIEVE_EDIT_PRODUCT';
const REQUEST_PRODUCT = 'REQUEST_PRODUCT';
const RECIEVE_PRODUCT = 'RECIEVE_PRODUCT';

export default {
    REQUEST_EDIT_PRODUCT,
    RECIEVE_EDIT_PRODUCT,
    REQUEST_PRODUCT,
    RECIEVE_PRODUCT,
}