const REQUEST_DASHBOARD = 'REQUEST_DASHBOARD';
const RECIEVE_DASHBOARD = 'RECIEVE_DASHBOARD';
const REQUEST_DELETE_PRODUCT = 'REQUEST_DELETE_PRODUCT';
const RECIEVE_DELETE_PRODUCT = 'RECIEVE_DELETE_PRODUCT';
export default {
    REQUEST_DASHBOARD,
    RECIEVE_DASHBOARD,
    REQUEST_DELETE_PRODUCT,
    RECIEVE_DELETE_PRODUCT
}