const REQUEST_LANDING = 'REQUEST_LANDING';
const RECIEVE_LANDING = 'RECIEVE_LANDING';
const REQUEST_SUBSCRIBE = 'REQUEST_SUBSCRIBE';
const RECIEVE_SUBSCRIBE = 'RECIEVE_SUBSCRIBE';

export default {
    REQUEST_LANDING,
    RECIEVE_LANDING,
    REQUEST_SUBSCRIBE,
    RECIEVE_SUBSCRIBE
}