const REQUEST_ADD_PRODUCT = 'REQUEST_ADD_PRODUCT';
const RECIEVE_ADD_PRODUCT = 'RECIEVE_ADD_PRODUCT';
const REQUEST_PRODUCT = 'REQUEST_PRODUCT';
const RECIEVE_PRODUCT = 'RECIEVE_PRODUCT';

export default {
    REQUEST_ADD_PRODUCT,
    RECIEVE_ADD_PRODUCT,
    REQUEST_PRODUCT,
    RECIEVE_PRODUCT,
}